Cargo_system_01/Models/driver.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cargo_system_01.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class driver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public driver()
        {
            this.orders = new HashSet<order>();
        }
    
        public int driver_id { get; set; }
        public string name { get; set; }
        public string family { get; set; }
        public int cartype_id { get; set; }
        public int carproperty_id { get; set; }
        public string tel { get; set; }
        public string mobile { get; set; }
        public string adr { get; set; }
        public string shaba { get; set; }
        public string carimg { get; set; }
    
        public virtual carproperty carproperty { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }

        public virtual cartype cartype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
    }
}

Cargo_system_01/Controllers/driversController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Cargo_system_01.Models;
using System.IO;

namespace Cargo_system_01.Controllers
{
    public class driversController : Controller
    {
        private Cargo_system01Entities3 db = new Cargo_system01Entities3();

        // GET: drivers
        public ActionResult Index()
        {
            var drivers = db.drivers.Include(d => d.carproperty).Include(d => d.cartype);
            return View(drivers.ToList());
        }

        // GET: drivers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            driver driver = db.drivers.Find(id);
            if (driver == null)
            {
                return HttpNotFound();
            }
            return View(driver);
        }

        // GET: drivers/Create
        public ActionResult Create()
        {
            ViewBag.carproperty_id = new SelectList(db.carproperties, "carproperty_id", "name");
            ViewBag.cartype_id = new SelectList(db.cartypes, "cartype_id", "name");
            return View();
        }

        // POST: drivers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "driver_id,name,family,cartype_id,carproperty_id,tel,mobile,adr,shaba,ImageFile")] driver driver)
        {
            if (driver.ImageFile != null)
            {
                string fileName = Path.GetFileNameWithoutExtension(driver.ImageFile.FileName);
                string extension = Path.GetExtension(driver.ImageFile.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                driver.carimg = "~/Image/driver/" + fileName;
                fileName = Path.Combine(Server.MapPath("~/Image/driver/"), fileName);
                driver.ImageFile.SaveAs(fileName);
            }
            if (ModelState.IsValid)
            {
                db.drivers.Add(driver);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.carproperty_id = new SelectList(db.carproperties, "carproperty_id", "name", driver.carproperty_id);
            ViewBag.cartype_id = new SelectList(db.cartypes, "cartype_id", "name", driver.cartype_id);
            return View(driver);
        }

        // GET: drivers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            driver driver = db.drivers.Find(id);
            if (driver == null)
            {
                return HttpNotFound();
            }
            ViewBag.carproperty_id = new SelectList(db.carproperties, "carproperty_id", "name", driver.carproperty_id);
            ViewBag.cartype_id = new SelectList(db.cartypes, "cartype_id", "name", driver.cartype_id);
            return View(driver);
        }

        // POST: drivers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "driver_id,name,family,cartype_id,carproperty_id,tel,mobile,adr,shaba,carimg,ImageFile")] driver driver)
        {
            if (driver.ImageFile != null)
            {
                string fileName = Path.GetFileNameWithoutExtension(driver.ImageFile.FileName);
                string extension = Path.GetExtension(driver.ImageFile.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                driver.carimg = "~/Image/driver/" + fileName;
                fileName = Path.Combine(Server.MapPath("~/Image/driver/"), fileName);
                driver.ImageFile.SaveAs(fileName);
            }
            if (ModelState.IsValid)
            {
                db.Entry(driver).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.carproperty_id = new SelectList(db.carproperties, "carproperty_id", "name", driver.carproperty_id);
            ViewBag.cartype_id = new SelectList(db.cartypes, "cartype_id", "name", driver.cartype_id);
            return View(driver);
        }

        // GET: drivers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            driver driver = db.drivers.Find(id);
            if (driver == null)
            {
                return HttpNotFound();
            }
            return View(driver);
        }

        // POST: drivers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            driver driver = db.drivers.Find(id);
            db.drivers.Remove(driver);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Cargo_system_01/Views/drivers/Create.cshtml
@model Cargo_system_01.Models.driver

@{
    ViewBag.Title = "رانندگان";
    Layout = "~/Views/_AdminLayout.cshtml";
}
<br />
<br />
<br />


@using (Html.BeginForm("Create", "drivers", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="card card-primary centerbox">
        <div class="card-header">
            <h3 class="card-title">ایجاد راننده جديد</h3>
        </div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
                <div class="row card-body">
                    <label class="control-label col-md-2" for="name">نام:</label>
                    @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control col-md-9" } })
                    @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                </div>

                <div class="row card-body">
                    @Html.LabelFor(model => model.family,"نام خانوادگی:", htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.family, new { htmlAttributes = new { @class = "form-control col-md-9" } })
                    @Html.ValidationMessageFor(model => model.family, "", new { @class = "text-danger" })
                </div>

                <div class="row card-body">
                    @Html.LabelFor(model => model.cartype_id, "نوع ماشين:", htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.DropDownList("cartype_id", null, htmlAttributes: new { @class = "form-control col-md-9" })
                    @Html.ValidationMessageFor(model => model.cartype_id, "", new { @class = "text-danger" })
                </div>

                <div class="row card-body">
                    @Html.LabelFor(model => model.carproperty_id, "مدل ماشين:", htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.DropDownList("carproperty_id", null, htmlAttributes: new { @class = "form-control col-md-9" })
                    @Html.ValidationMessageFor(model => model.carproperty_id, "", new { @class = "text-danger" })
                </div>

                <div class="row card-body">
                    @Html.LabelFor(model => model.tel,"شماره تلفن:", htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.tel, new { htmlAttributes = new { @class = "form-control col-md-9" } })
                    @Html.ValidationMessageFor(model => model.tel, "", new { @class = "text-danger" })
                </div>

                <div class="row card-body">
                    @Html.LabelFor(model => model.mobile,"شماره موبایل:", htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.mobile, new { htmlAttributes = new { @class = "form-control col-md-9" } })
                    @Html.ValidationMessageFor(model => model.mobile, "", new { @class = "text-danger" })
                </div>

                <div class="row card-body">
                    @Html.LabelFor(model => model.adr,"آدرس:", htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.adr, new { htmlAttributes = new { @class = "form-control col-md-9" } })
                    @Html.ValidationMessageFor(model => model.adr, "", new { @class = "text-danger" })
                </div>

                <div class="row card-body">
                    @Html.LabelFor(model => model.shaba,"شماره شبا:", htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.shaba, new { htmlAttributes = new { @class = "form-control col-md-9" } })
                    @Html.ValidationMessageFor(model => model.shaba, "", new { @class = "text-danger" })
                </div>

                <div class="row card-body">
                    @Html.LabelFor(model => model.carimg,"تصویر خودرو:", htmlAttributes: new { @class = "control-label col-md-2" })
                    <input type="file" name="ImageFile" id="ImageFile">
                    @Html.ValidationMessageFor(model => model.carimg, "", new { @class = "text-danger" })
                </div>

                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="ثبت" class="btn btn-default" />
                    @Html.ActionLink("بازگشت", "Index", null, new { @class = "btn btn-primary" })
                </div>
        </div>
    </div>
}

<br />
<br />
<br />


<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Cargo_system_01/Views/drivers/Delete.cshtml
@model Cargo_system_01.Models.driver

@{
    ViewBag.Title = "رانندگان";
    Layout = "~/Views/_AdminLayout.cshtml";
}

<br />
<br />
<br />


<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4" style="margin-top:30px">
        <h3>آیا شما از حذف کردن این آیتم مطمئن هستید؟</h3>
        <h2>جزئیات نوع خودرو</h2>
        <div>
            <dl class="dl-horizontal">
                <dt>
                    نام راننده
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.name)
                </dd>

                <dt>
                    نام خانوادگی
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.family)
                </dd>

                <dt>
                    شماره تلفن
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.tel)
                </dd>

                <dt>
                    شماره موبایل
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.mobile)
                </dd>

                <dt>
                    آدرس
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.adr)
                </dd>

                <dt>
                    شماره شبا
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.shaba)
                </dd>
                @if (!string.IsNullOrWhiteSpace(Model.carimg))
                {
                    <dt>
                        تصویر خودرو
                    </dt>

                    <dd>
                        <img src="@Url.Content(Model.carimg)" width="250" height="250" multiple />
                    </dd>
                }
                <dt>
                    ویژگی بخش بار
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.carproperty.name)
                </dd>

                <dt>
                    نوع خودرو
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.cartype.name)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="حذف" class="btn btn-danger" /> |
                    @Html.ActionLink("بازگشت", "Index", null, new { @class = "btn btn-secondary" })
                </div>
            }
        </div>
    </div>
</div>

    <br />
    <br />
    <br />

Cargo_system_01/Views/drivers/Details.cshtml
@model Cargo_system_01.Models.driver

@{
    ViewBag.Title = "رانندگان";
    Layout = "~/Views/_AdminLayout.cshtml";
}

<
<br />
<br />
<br />

<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4" style="margin-top:30px">
        <h2>جزئیات راننده</h2>
        <div>
            <dl class="dl-horizontal">
                <dt>
نام راننده
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.name)
                </dd>

                <dt>
نام خانوادگی
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.family)
                </dd>

                <dt>
شماره تلفن
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.tel)
                </dd>

                <dt>
شماره موبایل
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.mobile)
                </dd>

                <dt>
آدرس
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.adr)
                </dd>

                <dt>
شماره شبا
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.shaba)
                </dd>
@if (!string.IsNullOrWhiteSpace(Model.carimg))
{
                <dt>
تصویر خودرو
                </dt>

                <dd>
                    <img src="@Url.Content(Model.carimg)" width="250" height="250" multiple />
                </dd>
}
                <dt>
ویژگی بخش بار
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.carproperty.name)
                </dd>

                <dt>
نوع خودرو
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.cartype.name)
                </dd>

            </dl>
        </div>
        <p>
            @Html.ActionLink("ویرایش", "Edit", new { id = Model.cartype_id }, new { @class = "btn btn-info" })
            @Html.ActionLink("بازگشت", "Index", null, new { @class = "btn btn-secondary" })
        </p>
    </div>
</div>

<br />
<br />
<br />

Cargo_system_01/Views/drivers/Edit.cshtml
@model Cargo_system_01.Models.driver

@{
    ViewBag.Title = "رانندگان";
    Layout = "~/Views/_AdminLayout.cshtml";
}

<br />
<br />
<br />


@using (Html.BeginForm("Edit", "drivers", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="card card-primary centerbox">
        <div class="card-header">
            <h3 class="card-title">ويرايش راننده جديد</h3>
        </div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.driver_id)
        @Html.HiddenFor(model => model.carimg)

        <div class="form-group">
            <div class="row card-body">
                <label class="control-label col-md-2" for="name">نام:</label>
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control col-md-9" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>

            <div class="row card-body">
                @Html.LabelFor(model => model.family, "نام خانوادگی:", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.family, new { htmlAttributes = new { @class = "form-control col-md-9" } })
                @Html.ValidationMessageFor(model => model.family, "", new { @class = "text-danger" })
            </div>

            <div class="row card-body">
                @Html.LabelFor(model => model.cartype_id, "نوع ماشين:", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.DropDownList("cartype_id", null, htmlAttributes: new { @class = "form-control col-md-9" })
                @Html.ValidationMessageFor(model => model.cartype_id, "", new { @class = "text-danger" })
            </div>

            <div class="row card-body">
                @Html.LabelFor(model => model.carproperty_id, "مدل ماشين:", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.DropDownList("carproperty_id", null, htmlAttributes: new { @class = "form-control col-md-9" })
                @Html.ValidationMessageFor(model => model.carproperty_id, "", new { @class = "text-danger" })
            </div>

            <div class="row card-body">
                @Html.LabelFor(model => model.tel, "شماره تلفن:", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.tel, new { htmlAttributes = new { @class = "form-control col-md-9" } })
                @Html.ValidationMessageFor(model => model.tel, "", new { @class = "text-danger" })
            </div>

            <div class="row card-body">
                @Html.LabelFor(model => model.mobile, "شماره موبایل:", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.mobile, new { htmlAttributes = new { @class = "form-control col-md-9" } })
                @Html.ValidationMessageFor(model => model.mobile, "", new { @class = "text-danger" })
            </div>

            <div class="row card-body">
                @Html.LabelFor(model => model.adr, "آدرس:", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.adr, new { htmlAttributes = new { @class = "form-control col-md-9" } })
                @Html.ValidationMessageFor(model => model.adr, "", new { @class = "text-danger" })
            </div>

            <div class="row card-body">
                @Html.LabelFor(model => model.shaba, "شماره شبا:", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.shaba, new { htmlAttributes = new { @class = "form-control col-md-9" } })
                @Html.ValidationMessageFor(model => model.shaba, "", new { @class = "text-danger" })
            </div>

            <div class="row card-body">
                @Html.LabelFor(model => model.carimg, "تصویر خودرو:", htmlAttributes: new { @class = "control-label col-md-2" })
                <input type="file" name="ImageFile" id="ImageFile">
                @Html.ValidationMessageFor(model => model.carimg, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ثبت" class="btn btn-default" />
                @Html.ActionLink("بازگشت", "Index", null, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>

}
<br />
<br />
<br />


<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Cargo_system_01/Views/drivers/Index.cshtml
@model IEnumerable<Cargo_system_01.Models.driver>

@{
    ViewBag.Title = "رانندگان";
    Layout = "~/Views/_AdminLayout.cshtml";
}

<div class="card-body">
    <h2>رانندگان</h2>

    <p>
        @Html.ActionLink("ایجاد راننده", "Create", null, new { @class = "btn btn-success" })
    </p>
    <div class="card-body">
        <table id="grid" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>
نام راننده
                    </th>
                    <th>
نام خانوادگی
                    </th>
                    <th>
شماره تلفن
                    </th>
                    <th>
شماره موبایل
                    </th>
                    <th>
آدرس
                    </th>
                    <th>
شماره شبا
                    </th>
                    <th>
ویژگی بخش بار
                    </th>
                    <th>
نوع خودرو
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.family)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.tel)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.mobile)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.adr)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.shaba)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.carproperty.name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.cartype.name)
                        </td>
                        <td>
                            @Html.ActionLink("ویرایش", "Edit", new { id = item.driver_id }, new { @class = "btn btn-info" }) |
                            @Html.ActionLink("جزیات", "Details", new { id = item.driver_id }, new { @class = "btn btn-warning" }) |
                            @Html.ActionLink("حذف", "Delete", new { id = item.driver_id }, new { @class = "btn btn-danger" })
                        </td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>