Cargo_system_01/Controllers/search_order_statusController.cs
using Cargo_system_01.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Cargo_system_01.Controllers
{
    public class search_order_statusController : Controller
    {
        private Cargo_system01Entities3 db = new Cargo_system01Entities3();

        // GET: search_order_status
        public ActionResult Indexes()
        {
            //this.ViewData["loadstatus"] = db.loadstatus.ToList();
            ViewBag.loadstatus = new SelectList(db.loadstatus, "loadstatus_id", "name");

            return View(db.View_orders);
        }

        [HttpPost]
        public ActionResult Index(int id)
        {

            //if (Request.Form["text"] == null)  
            //{  
            //    TempData["SelectOption"] = -1;  
            //}             
            ViewBag.loadstatus = new SelectList(db.loadstatus, "loadstatus_id", "name");
            return View(db.sp_orders_status(id));
        }
    }
}

Cargo_system_01/Views/search_order_status/index.cshtml
@model IEnumerable<Cargo_system_01.Models.sp_orders_status_Result>

@{
    ViewBag.Title = "گزارش وضعيت سفارش";
    Layout = "~/Views/_AdminLayout.cshtml";
}

<div class="card-body">
    <h2>گزارش وضعيت سفارش</h2>
        @using (Html.BeginForm("Index", "search_order_status", FormMethod.Post))
        {
            <br />
            <div class="card-tools d-flex">
                <div class="col-md-2"></div>
                <span style="margin-top:5px">انتخاب نوع ماشين:</span>
                    @Html.DropDownList("id",
                    (IEnumerable<SelectListItem>)ViewBag.loadstatus,
                    "انتخاب وضعيت ارسال",
                    new { @class = "col-md-6 form-control"})
                <input type="submit" class="btn btn-md btn-success" value="جستجو" />
            </div>
            <br />
        }
        <div class="card-body" style="overflow: auto;white-space: nowrap;">
            <table id="grid" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>
                            نام راننده
                        </th>
                        <th>
                            نام خانوادگی راننده
                        </th>
                        <th>
                            شماره تلفن راننده
                        </th>
                        <th>
                            شماره سفارش
                        </th>
                        <th>
                            آدرس فرستنده
                        </th>
                        <th>
                            نام فرستنده
                        </th>
                        <th>
                            موبایل فرستنده
                        </th>
                        <th>
                            تاریخ ارسال
                        </th>
                        <th>
                            شهر ارسال
                        </th>
                        <th>
                            نام گیرنده
                        </th>
                        <th>
                            موبایل گیرنده
                        </th>
                        <th>
                            تاریخ دریافت
                        </th>
                        <th>
                            شهر مقصد
                        </th>
                        <th>
                            نوع بار
                        </th>
                        <th>
                            نوع بسته بندی
                        </th>
                        <th>
                            وزن بار
                        </th>
                        <th>
                            تاریخ دریافت بار راننده
                        </th>
                        <th>
                            وضعیت بار
                        </th>
                        <th>
                            توضیحات
                        </th>
                        <th>
                            نام مشتری
                        </th>
                        <th>
                            نام خانوادگی مشتری
                        </th>
                        <th>
                            موبایل مشتری
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.driver_name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.driver_family)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.driver_mobile)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.orders_id)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.from_adr)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.from_name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.from_mobile)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.from_date)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.from_city)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.to_name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.to_mobile)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.to_date)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.to_city)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.load_type)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.package_type)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.load_weight)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.driver_date)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.order_status)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.description)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.customer_name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.customer_family)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.customer_mobile)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
</div>

Cargo_system_01/Views/search_order_status/indexes.cshtml
@model IEnumerable<Cargo_system_01.Models.View_orders>

@{
    ViewBag.Title = "گزارش وضعيت سفارش";
    Layout = "~/Views/_AdminLayout.cshtml";
}

<div class="card-body">
    <h2>گزارش وضعيت سفارش</h2>
        @using (Html.BeginForm("Index", "search_order_status", FormMethod.Post))
        {
            <br />
            <div class="card-tools d-flex">
                <div class="col-md-2"></div>
                <span style="margin-top:5px">انتخاب وضعيت ارسال:</span>
                    @Html.DropDownList("id",
                    (IEnumerable<SelectListItem>)ViewBag.loadstatus,
                    new { @class = "col-md-6 form-control"})
                <input type="submit" class="btn btn-md btn-success" value="جستجو" />
            </div>
            <br />
        }
        <div class="card-body" style="overflow: auto;white-space: nowrap;">
            <table id="grid" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>
                            نام راننده
                        </th>
                        <th>
                            نام خانوادگی راننده
                        </th>
                        <th>
                            شماره تلفن راننده
                        </th>
                        <th>
                            شماره سفارش
                        </th>
                        <th>
                            آدرس فرستنده
                        </th>
                        <th>
                            نام فرستنده
                        </th>
                        <th>
                            موبایل فرستنده
                        </th>
                        <th>
                            تاریخ ارسال
                        </th>
                        <th>
                            شهر ارسال
                        </th>
                        <th>
                            نام گیرنده
                        </th>
                        <th>
                            موبایل گیرنده
                        </th>
                        <th>
                            تاریخ دریافت
                        </th>
                        <th>
                            شهر مقصد
                        </th>
                        <th>
                            نوع بار
                        </th>
                        <th>
                            نوع بسته بندی
                        </th>
                        <th>
                            وزن بار
                        </th>
                        <th>
                            تاریخ دریافت بار راننده
                        </th>
                        <th>
                            وضعیت بار
                        </th>
                        <th>
                            توضیحات
                        </th>
                        <th>
                            نام مشتری
                        </th>
                        <th>
                            نام خانوادگی مشتری
                        </th>
                        <th>
                            موبایل مشتری
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.driver_name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.driver_family)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.driver_mobile)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.orders_id)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.from_adr)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.from_name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.from_mobile)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.from_date)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.from_city)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.to_name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.to_mobile)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.to_date)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.to_city)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.load_type)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.package_type)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.load_weight)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.driver_date)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.order_status)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.description)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.customer_name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.customer_family)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.customer_mobile)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
</div>